package com.backend.Projet.model;

public enum NotificationType {
    TASK_OFFER,
    TASK_SELECTED,
    TASK_ACCEPTED,
    TASK_REFUSED,
    WORKER_ASSISTANCE_REQUEST,
    ADMIN_TASK_REVIEW,
    ADMIN_WORKER_REVIEW,
    WORKER_VERIFIED,
    WORKER_REJECTED,
    BOOKING_REQUEST,
    BOOKING_ACCEPTED,
    BOOKING_REJECTED,
    BOOKING_COMPLETED,
    BOOKING_CANCELLED
}
